Regex to allow hostnames as well as IP addresses
I have modified the regex to support obtaining "host.name.com" from '/_nodes/_all/clear' when using elasticsearch's sniff functionality.

e.g.
"http_address":"inet[host.name.com/1.2.3.4:443]"

I needed this because I am using a wildcard SSL certificate behind an nginx proxy and the current implementation produces:

SSLError: ConnectionError(hostname u'1.2.3.4' doesn't match either of '*.name.com', 'name.com') caused by: SSLError(hostname u'1.2.3.4' doesn't match either of '*.name.com', 'name.com')

Using this regex so the client uses the hostname to connect instead of the IP address solved my problem.