self.connections needs to be an array not a tuple
When connecting to a single host in a cluster with sniffing enabled, it tried to add all the cluster members to the DummyConnectionPool. This then fails with:

TypeError: can only concatenate list (not "tuple") to list

Changing the connections to an array in the constructor gets it working...